language: php

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

dist: trusty

matrix:
  include:
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE CORE_PATCH=core35.diff
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE CORE_PATCH=core35.diff
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE CORE_PATCH=core36.diff
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE CORE_PATCH=core36.diff
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE CORE_PATCH=core37.diff
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE CORE_PATCH=core37.diff
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv
  - if [ ! -z "$CORE_PATCH" ]; then (cd /home/travis/build/moodle; git apply admin/tool/mfa/patch/$CORE_PATCH); fi

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
